import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative flex items-center justify-center w-full">
        <Navbar/>
        </div>
        <Toaster position="top-center" />
        {children}
        </body>
    </html>
  );
}



